#!/usr/bin/env python3
"""Build the deployable pages for 123 Snake.

Sources (edit these):
  123-snake.html       the game UI (also published verbatim as the artifact)
  solver/lab-src.html  the solver lab UI, with a __WASM_B64__ placeholder

Outputs (generated - do not edit by hand):
  solver/solver-lab.html  lab with the compiled wasm engine embedded
  docs/index.html         GitHub Pages site (game wrapped in a full document)

Run after any change to the Rust engine or either source file:
  python3 build.py
"""

import base64
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).parent
GENERATED = "<!-- GENERATED by build.py - edit {src} instead -->\n"

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>123 Snake</title>
<meta name="description" content="123 Snake — drag chains of matching numbers and merge them into their sum. A recreation of the 2016 mobile puzzle Integer Snake.">
<meta property="og:title" content="123 Snake">
<meta property="og:description" content="Drag chains of matching numbers and merge them into their sum. How high can you score?">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' rx='22' fill='%23F6DC7D'/%3E%3Ctext x='50' y='72' font-size='62' font-weight='bold' text-anchor='middle' font-family='Arial'%3E2%3C/text%3E%3C/svg%3E">
</head>
<body>
"""


def build_wasm() -> str:
    subprocess.run(
        [
            "cargo", "build", "--profile", "wasm-release",
            "--target", "wasm32-unknown-unknown", "--lib",
        ],
        check=True,
        cwd=ROOT,
    )
    wasm = ROOT / "target/wasm32-unknown-unknown/wasm-release/integer_snake.wasm"
    return base64.b64encode(wasm.read_bytes()).decode()


def build_lab(b64: str) -> None:
    src = (ROOT / "solver/lab-src.html").read_text()
    assert "__WASM_B64__" in src, "lab-src.html is missing the wasm placeholder"
    out = GENERATED.format(src="solver/lab-src.html") + src.replace("__WASM_B64__", b64)
    (ROOT / "solver/solver-lab.html").write_text(out)
    print(f"solver/solver-lab.html  {len(out):>8} bytes")


def build_site() -> None:
    game = (ROOT / "123-snake.html").read_text()
    # the game source starts with its <title>, which moves into <head>
    title = "<title>123 Snake</title>\n"
    assert game.startswith(title), "123-snake.html must start with its <title>"
    out = (
        GENERATED.format(src="123-snake.html")
        + HEAD
        + game[len(title):]
        + "</body>\n</html>\n"
    )
    (ROOT / "docs/index.html").write_text(out)
    print(f"docs/index.html         {len(out):>8} bytes")


if __name__ == "__main__":
    b64 = build_wasm()
    print(f"wasm engine             {len(b64):>8} bytes (base64)")
    build_lab(b64)
    build_site()
